
name: Node.js CI-CD Pipeline

on:
  push:
    branches:
      - main
      - github-actions
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: aljozy/assignment-problem
          ref: main

      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

     
      - name: Build Docker image
        run: |
          cd node-app
          docker buildx build . -t prev:v1 --load


      - name: Run Docker container
        run: |
          docker run -d --rm -p 3000:3000 prev:v1